### ISSUE TITLE
Contribute solutions of Coding Ninjas' problems

### ISSUE THREAD

**Issue by MohammedHamzaMalik** [MohammedHamzaMalik/Coding-Ninjas-Competitive-Programming#1]
Contribute the solutions to Coding Ninjas' Competitive Programming course problems.

Only add the solutions in Python and Cpp language only.

**Comment by Danuragtiwari** [comment]
@MohammedHamzaMalik please assign to me!

**Comment by MohammedHamzaMalik** [comment]
Ok, @Danuragtiwari I am assigning you this issue.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by THE-AryanKumar** [comment]
@MohammedHamzaMalik can you assign me...

**Comment by MohammedHamzaMalik** [comment]
Sure @THE-AryanKumar, you can now work on this issue.

Read the **contributing.md** file first.

Add the problems' explanation and code in its course specific folder with the file name as **"{problem-name}.cpp"** or **"{problem-name}.py"**

For reference, check out the previously added problems' solution.

**Comment by Divya5003** [comment]
Hey @MohammedHamzaMalik , i want to work on this issue.

**Comment by MohammedHamzaMalik** [comment]
It is assigned to you @Divya5003 , start working on it.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by VishalManam** [comment]
Hello @MohammedHamzaMalik, please assign me this issue.

**Comment by MohammedHamzaMalik** [comment]
Sure @VishalManam 

> Hello @MohammedHamzaMalik, please assign me this issue.

**Comment by MohammedHamzaMalik** [comment]
@VishalManam 

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solutions.

**Comment by kshavgupta** [comment]
Hello @MohammedHamzaMalik , please assign this issue to me, I will make the solutions to the problem in **C++**.

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @keshav-guptaa 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by Arika008** [comment]
Please check PR #20

**Comment by Ayashika** [comment]
hello @MohammedHamzaMalik, I would love to add c++ solutions to coding Ninja problems, please assign this issue to me.

**Comment by MohammedHamzaMalik** [comment]
Sure @Ayashika

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @Ayashika 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by kshavgupta** [comment]
@MohammedHamzaMalik please merge my PR #22

**Comment by MohammedHamzaMalik** [comment]
> Please check PR #20

Add solutions along with a complete explanation of the problem and add the CPP or python file in the specific topic folder only.

**Comment by r5b6** [comment]
@MohammedHamzaMalik, please assign me this issue.

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @r5b6 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by kshavgupta** [comment]
Please merge my PR #25

**Comment by MohammedHamzaMalik** [comment]
> Please merge my PR #25

PR merged.

**Comment by Anand-shreya** [comment]
please assign me this issue

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @Anand-shreya 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by SanyamAgrawal07** [comment]
Hii @MohammedHamzaMalik , please assign me this issue

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @SanyamAgrawal07 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by dis-28** [comment]
hello please assign me this issue, I would like to contribute

**Comment by MohammedHamzaMalik** [comment]
> hello please assign me this issue, I would like to contribute

Sure @dis-28

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @dis-28 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by SanyamAgrawal07** [comment]
@MohammedHamzaMalik Please check my PR #33

**Comment by MohammedHamzaMalik** [comment]
> @MohammedHamzaMalik Please check my PR #33

PR merged

**Comment by kshavgupta** [comment]
Please merge my PR #34

**Comment by MohammedHamzaMalik** [comment]
> Please merge my PR #34

PR merged

**Comment by Deeya13** [comment]
please assign this issue to me.

**Comment by dis-28** [comment]
please merge my PR #37

**Comment by MohammedHamzaMalik** [comment]
PR merged 

> please merge my PR #37
