### ISSUE TITLE
Contribute solutions of Coding Ninjas' Competitive Programming course 

### ISSUE THREAD

**Issue by MohammedHamzaMalik** [MohammedHamzaMalik/Coding-Ninjas-Competitive-Programming#17]
Contribute the solutions to Coding Ninjas' Competitive Programming course problems.

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by VishalManam** [comment]
Please assign me this issue.

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @VishalManam 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by singhpratapaayush07** [comment]
Hi , please assign this issue to me

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @singhpratapaayush07 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by ashish5433** [comment]
hey @MohammedHamzaMalik i want to add a program of coding ninjas pls assign this to me

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @ashish5433 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by Anand-shreya** [comment]
Can you please assign this to me also, I want to contribute.

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @Anand-shreya 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by dis-28** [comment]
hello I would like to contribute please assign me this issue

**Comment by MohammedHamzaMalik** [comment]
Issue assigned to @dis-28 

Only add the solutions in Python and Cpp language only.

Read the contributing.md file first.

Add the problems' explanation and code in its course specific folder with the file name as "{problem-name}.cpp" or "{problem-name}.py"

For reference, check out the previously added problems' solution.

**Comment by dis-28** [comment]
please merge my PR #39

**Comment by MohammedHamzaMalik** [comment]
PR merged 

> please merge my PR #39

**Comment by dis-28** [comment]
please merge my PR #40
