### ISSUE TITLE
add a contributing file

### ISSUE THREAD

**Issue by MohammedHamzaMalik** [MohammedHamzaMalik/Coding-Ninjas-Competitive-Programming#2]
Add a contributing file in markdown format which describes how to contribute to this repository.
Also mention the issue in the description of the PR

**Comment by apoorva1823000** [comment]
Hi can I work on this issue ?

**Comment by MohammedHamzaMalik** [comment]
Hey @apoorva1823000, I have already created the file and solved this issue.

But if you want to work on this issue, you can modify the existing contributing file.

**Comment by apoorva1823000** [comment]
ok, thanks
as a matter of fact, would that modification (if accepted by you) be considered as valid pr for hacktoberfest ?
